version: '3.9'

services: 
  myadmin:
    image: phpmyadmin:latest
    ports:
      - 9090:80
    environment: 
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    depends_on: 
      - database
  
  database:
    image: mysql:latest
#    ports:
#      - 3306:3306
    volumes:
      - d:\formation\docker\ynov\maj2\myadmin\mysql:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DEFAULT_DB_NAME}
      MYSQL_USER: bob
      MYSQL_PASSWORD: boby